export const typeKorean = {
    normal: '노말',
    fire: '불꽃',
    water: '물',
    electric: '전기',
    grass: '풀',
    ice: '얼음',
    fighting: '격투',
    poison: '독',
    ground: '땅',
    flying: '비행',
    psychic: '에스퍼',
    bug: '벌레',
    rock: '바위',
    ghost: '고스트',
    dragon: '드래곤',
    dark: '악',
    steel: '강철',
    fairy: '페어리',
};

// 타입별 색상
export const typeColors = {
    normal: '#E8E4D9',
    fire: '#FFBFA3',
    water: '#A8D5E2',
    grass: '#B8E6B8',
    electric: '#FFE699',
    ice: '#D4EFEF',
    fighting: '#FFB3B3',
    poison: '#E6BFFF',
    ground: '#E6D7A3',
    flying: '#D9CFFF',
    psychic: '#FFB3D9',
    bug: '#D9E699',
    rock: '#D9CDB3',
    ghost: '#D4C4E6',
    dragon: '#BFB3FF',
    dark: '#C9B8A8',
    steel: '#D9D9E6',
    fairy: '#FFD9F2',
};
